### ISSUE TITLE
[bug] one `l` gets removed from words like `all`

### ISSUE THREAD

**Issue by iamtalhaasghar** [lgomezt/Tidytweets#2]
```
>>> tp.preprocess('all tasks were completed')
'al tasks were completed'
```

expected output:
`all tasks were completed`

Great work btw!

**Comment by lgomezt** [comment]
You're correct! Since the package was primarily designed for processing Spanish text, I hadn't considered words like "all", which end in repeated letters. This issue has been addressed in version 1.7.0 of tidyX. In this update, the exceptions parameter for `tp.preprocess()`, `tp.remove_repetitions()`, and `tp.remove_last_repetition()` now includes a default list of characters such as `["r", "l", "n", "c", "a", "e", "o"]`. This change aims to properly handle cases like 'all tasks were completed'. For example, if you input 'alllll taskss were completed' into `tp.preprocess()`, it will now correctly return 'all tasks were completed.' 

For more details see the commit db3545827fcc15115affd28c5fe6e5edad2aee52

**Comment by iamtalhaasghar** [comment]
We should have a flag called `allow_repetitions` which then can be used to allow or disallow repetitions. If enabled, we should bypass `remove_last_repetition` and `remove_repetition` functions. 
I was just doing this and saw notification that you did a patch. If I were to open Pull Request will you merge it?

**Comment by lgomezt** [comment]
Of course!
